<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Title>Avalonia.Container</Title>
    <Authors>Mario</Authors>
    <Company>Real</Company>
    <Description>DialogService, NavigationService</Description>
    <PackageIcon>자산 3@4x.png</PackageIcon>
    <PackageTags>7.0;8.0;9.0</PackageTags>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>1.2.5</Version>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.3.9" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.9" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.9" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Include="Avalonia.Diagnostics" Version="11.3.9">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Container.Core\Container.Core.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="자산 3@4x.png">
	    <PackagePath>\</PackagePath>
	    <Pack>True</Pack>
	  </Resource>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Dialog\DialogServiceExtension.cs">
	    <SubType>Code</SubType>
	  </Compile>
	  <Compile Update="Navigate\NavigationServiceExtension.cs">
	    <SubType>Code</SubType>
	  </Compile>
	</ItemGroup>
</Project>
